apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml
  - clusterrolebinding.yaml

images:
  - name: wiz-panel-images
    newName: 637423347157.dkr.ecr.us-east-1.amazonaws.com/wiz-panel-images
    newTag: latest
