apiVersion: v1
kind: Secret
metadata:
  name: wiz-app-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:ChangeMe123!@10.50.1.42:27017/?authSource=admin"
  SECRET_KEY: "wiz-panel-secret-key"
