apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wiz-app-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: wiz-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: Wiz-Labs-297-wiz-app
        property: MONGODB_URI
    - secretKey: SECRET_KEY
      remoteRef:
        key: Wiz-Labs-297-wiz-app
        property: SECRET_KEY
