name: Trivy Container Scan

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Build image for scanning
        run: docker build . -f Dockerfile -t wiz-app:scan

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: wiz-app:scan
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH
          output: trivy-results.txt

      - name: Post scan results to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: trivy-scan
          path: trivy-results.txt
